"""Hello Bro

Revision ID: 82b0c66d7541
Revises: 87445980c9c0
Create Date: 2025-06-20 18:36:46.082494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b0c66d7541'
down_revision = '87445980c9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
