"""your message

Revision ID: 87445980c9c0
Revises: 
Create Date: 2025-06-20 18:32:40.805372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87445980c9c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
