"""your message

Revision ID: d4e09d76e756
Revises: 5a57aad5fe9d
Create Date: 2025-06-20 19:42:18.330447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e09d76e756'
down_revision = '5a57aad5fe9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
